# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hRw3YWa9--eU_x-zEJxxyz_TAqd_x0M
"""



import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
from scipy.stats import norm
from scipy.stats import binom

#number of simulations
simulations=10000

#number of lottery tickets in each stimulation are
n =  50

#Probability of  winning a lottery
p = 1/100

#Simulating Event 
data_binom = binom.rvs(n,p,size=simulations)

win_atleast_1=0
win_atleast_2=0
for i in range(10000):
    if data_binom[i]>=1:
       win_atleast_1 +=1
    if data_binom[i]>=2:
      win_atleast_2 +=1



print("Probability of winning atleast one lottery ticket via simulations is :",win_atleast_1/simulations)
print("Probability of winnint atleast one lottery ticket theoritically is:",0.39499394)
print("Probability of winning exact one lottery ticket via simulations is ",(win_atleast_1-win_atleast_2)/simulations)
print("Probability of winning exact one lottery ticket theoritically is:",0.30555861)
print("Probability of winning atleast two lottery ticket via simulations is:",win_atleast_2/simulations)
print("Probability of wining at least two lottery ticket theoritically is: ",0.08943555)



